import { supabase } from "@/utils/supabase";
import * as FileSystem from "expo-file-system/legacy";
import { Post } from "@/types/ui-models";
import { Circle } from "react-native-maps";

export interface PostAPI {
    id?: string; // optional, generated by DB
    userId: string;
    
    created_at?: string; // optional, DB-generated timestamp
    updated_at?: string; // optional, DB-generated timestamp
    
    location_id?: string | null;
  
    title: string;
    short_description?: string | null;
    description?: string | null;
    how_to_find_us?: string | null;
  
    start_date?: string | null; // YYYY-MM-DD
    end_date?: string | null; // YYYY-MM-DD
    start_time?: string | null; // "HH:MM:SS"
    end_time?: string | null;   // "HH:MM:SS"
    is_multi_day?: boolean;
  
    pricing_type?: "free" | "rsvp" | "paid";
    cost?: number | null;
    ticket_link?: string | null;
    refund_policy?: string | null;
    refund_policy_link?: string | null;
  
    postRankId?: string | null;
  
    image_urls?: string[] | null;
    tags?: string[] | null;
  }

/**
 * Helper: Upload a single image to Supabase Storage using FileSystem legacy API
 */
async function uploadImage(
  uri: string,
  userId: string,
  postId: string,
  index: number
): Promise<string | null> {
  try {
    console.log(`📤 Uploading image ${index + 1}:`, uri);

    const fileName = uri.split("/").pop() || `image-${Date.now()}.jpg`;
    const fileExt = uri.split(".").pop()?.toLowerCase() || "jpg";
    const filePath = `posts/${Date.now()}_${index}-${fileName}`; // Changed path format

    // Check if file exists using legacy API
    const fileInfo = await FileSystem.getInfoAsync(uri);
    if (!fileInfo.exists) {
      throw new Error(`File not found at URI: ${uri}`);
    }

    // Read file as base64 using legacy API
    const base64 = await FileSystem.readAsStringAsync(uri, {
      encoding: FileSystem.EncodingType.Base64,
    });

    // Convert base64 to binary
    const binary = Uint8Array.from(atob(base64), (c) => c.charCodeAt(0));

    console.log(`📁 Uploading to: ${filePath}`);

    // Upload to Supabase Storage - FIXED: Use "images" bucket instead of "post-images"
    const { error } = await supabase.storage
      .from("images") // Changed from "post-images" to "images"
      .upload(filePath, binary, {
        contentType: `image/${fileExt}`,
        cacheControl: "3600",
        upsert: false,
      });

    if (error) {
      console.error(`❌ Upload error for image ${index + 1}:`, error);
      throw error;
    }

    // Get public URL - FIXED: Use "images" bucket
    const { data } = supabase.storage.from("images").getPublicUrl(filePath);
    console.log(`✅ Image ${index + 1} uploaded:`, data.publicUrl);
    return data.publicUrl;
  } catch (err) {
    console.error(`❌ Failed to upload image ${index + 1}:`, err);
    return null;
  }
}

/**
 * Create a post with images
 */
export async function createPostWithImages(postData: Post) {
    try {
      console.log("🚀 Starting post creation...");
  
      // CREATE LOCATION OBJECT IF
      let locationId: string | null = null;
      if (postData.location != null) {
        const { data: loc, error: locErr } = await supabase
          .from("locations")
          .insert({
            name: postData.location.name,
            address: postData.location.address || null,
            city: postData.location.city || null,
            state: postData.location.state || null,
            country: postData.location.country || null,
            zip_code: postData.location.postal_code || null,
            latitude: postData.location.latitude,
            longitude: postData.location.longitude,
          })
          .select("id")
          .single();
  
        if (locErr) throw locErr;
        locationId = loc.id;
        console.log("✅ Location created:", locationId);
      }
  
      // 2. Create post without images first
      const { data: post, error: postErr } = await supabase
        .from("posts")
        .insert({
          userId: postData.userId,
          location_id: locationId,
          title: postData.title,
          short_description: postData.short_description || null,
          description: postData.description || null,
          how_to_find_us: null,
          tags: postData.tags || null,
          start_date: postData.start_date,
          end_date: postData.end_date || null,
          start_time: postData.start_time,
          end_time: postData.end_time,
          is_multi_day: false,
          pricing_type: postData.pricing_type || "free",
          cost: postData.cost || null,
          ticket_link: postData.ticket_link || null,
          refund_policy: postData.refund_policy || null,
          refund_policy_link: postData.refund_policy_link || null,
          image_urls: null, // Will update after upload
        })
        .select("id")
        .single();
  
      if (postErr) throw postErr;
      console.log("✅ Post created:", post.id);
  
      // 3. Upload images if any
      const imageUris = postData.image_urls || [];
      if (imageUris.length > 0) {
        console.log(`📸 Uploading ${imageUris.length} images...`);
  
        const uploadPromises = imageUris.map((uri, index) =>
          uploadImage(uri, postData.userId, post.id, index)
        );
  
        const uploadedUrls = await Promise.all(uploadPromises);
        const validUrls = uploadedUrls.filter((url): url is string => url !== null);
  
        console.log(
          `✅ ${validUrls.length}/${imageUris.length} images uploaded successfully`
        );
  
        // Update post with image URLs
        if (validUrls.length > 0) {
          const { error: updateErr } = await supabase
            .from("posts")
            .update({ image_urls: validUrls })
            .eq("id", post.id);
  
          if (updateErr) console.error("❌ Failed to update post with image URLs:", updateErr);
          else console.log("✅ Post updated with image URLs");
        }
      }
  
      console.log("🎉 Post creation complete!");
      return post;
    } catch (err) {
      console.error("❌ Error in createPostWithImages:", err);
      throw err;
    }
  }
  